spring:
  kafka:
    bootstrap-server: localhost:9092
    consumer:
      group-id: ${spring.application.name}
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json:
          trusted.pakages: com.taha.linkedin.*