spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/v1/users/**
              filters:
                - StripPrefix=3

            - id: post-service
              uri: lb://POST-SERVICE
              predicates:
                - Path=/api/v1/posts/**
              filters:
                - StripPrefix=3
                - name: AuthenticationFilter

            - id: connection-service
              uri: lb://CONNECTION-SERVICE
              predicates:
                - Path=/api/v1/connections/**
              filters:
                - StripPrefix=3
                - name: AuthenticationFilter

server:
  port: 8080

jwt:
  secretKey: ${JWT_SECRET_KEY}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/