spring.application.name: api-gateway

server.port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
          filters:
            - StripPrefix=2

        - id: post-service
          uri: lb://POST-SERVICE
          predicates:
            - Path=/api/v1/posts/**
          filters:
            - StripPrefix=2

        - id: connection-service
          uri: lb://CONNECTION-SERVICE
          predicates:
            - Path=/api/v1/posts/**
          filters:
            - StripPrefix=2