spring.application.name=post-service

server.servlet.context-path=/posts
server.port=9010

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.datasource.url=jdbc:postgresql://localhost:5432/postsDB
spring.datasource.username= ${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update