spring.application.name=posts-service

server.servlet.context-path=/core
server.port=9010

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.datasource.url=jdbc:postgresql://localhost:5432/postsDB
spring.datasource.username= ${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update