spring.application.name=connection-service

server.servlet.context.path=/connections
server.port=9030

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.neo4j.uri=bolt://localhost:7687
spring.neo4j.authentication.username= ${DB_USERNAME}
spring.neo4f.authentication.password= ${DB_PASSWORD}