spring.application.name=user-service

server.servlet.context.path=/users
server.port = 9020

jwt.secretKey = asdfladf98a7df89aysf8d9yasiudfha9s87dfa89syudhfa98sdfyaisuhdfa98sfy

spring.datasource.url=jdbc:postgresql://localhost:5432/usersDB
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=create-drop