spring.application.name=user-service

#server.servlet.context-path=/users
server.port=9020
jwt.secretKey=${JWT_SECRET_KEY}

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.datasource.url=jdbc:postgresql://localhost:5432/usersDB
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=create-drop